name: test

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make Build
        uses: blenderkit/blender-addon-build@main
        with:
          exclude-files: ".github"
